version: "3.7"

services:
  mariadb:
    image: "wodby/mariadb:${MARIADB_TAG}"
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  php:
    image: "wodby/drupal-php:${PHP_TAG}"
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      DB_PREFIX: $DB_PREFIX
      DB_COLLATION: $DB_COLLATION
      DRUSH_OPTIONS_URI: "http://${PROJECT_BASE_URL}:${TRAEFIK_HTTP_PORT}"
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: debug
      PHP_IDE_CONFIG: "serverName=${PROJECT_BASE_URL}"
      PHP_XDEBUG_IDEKEY: $PHP_XDEBUG_IDEKEY
      PHP_XDEBUG_CLIENT_HOST: $PHP_XDEBUG_CLIENT_HOST
      PHP_XDEBUG_LOG: "/tmp/php-xdebug.log"
      SIMPLETEST_BASE_URL: "http://nginx"
      SIMPLETEST_DB: "${DB_DRIVER}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}#tests_"
      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","goog:chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chrome:9515"]'
    volumes:
      - ./:/var/www/html:cached

  crond:
    image: "wodby/drupal-php:${PHP_TAG}"
    container_name: "${PROJECT_NAME}_crond"
    environment:
      CRONTAB: "0 * * * * drush -r /var/www/html/web cron"
    command: sudo -E LD_PRELOAD=/usr/lib/preloadable_libiconv.so crond -f -d 0
    volumes:
      - ./:/var/www/html:cached

  nginx:
    image: "wodby/nginx:${NGINX_TAG}"
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
      - ./:/var/www/html:cached
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

  chrome:
    image: "selenium/standalone-chrome:${SELENIUM_CHROME_TAG}"
    container_name: "${PROJECT_NAME}_chrome"
    volumes:
    - /dev/shm:/dev/shm
    entrypoint:
    - chromedriver
    - "--no-sandbox"
    - "--disable-dev-shm-usage"
    - "--log-path=/tmp/chromedriver.log"
    - "--verbose"
    - "--whitelisted-ips="

  traefik:
    image: "traefik:${TRAEFIK_TAG}"
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - "${TRAEFIK_HTTP_PORT}:80"
      - "${TRAEFIK_DASHBOARD_PORT}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
